version: '3'
services:
  app:
    image: php:7-fpm
    volumes:
        - ./src/:/var/phpapp/
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf